version: '3'
services:
  db:
    restart: always
    image: postgres:10.3
    environment:
      - POSTGRES_USER=govoteuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=GoVoteGSO
    ports:
      - 9001:5432
  govote:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_TABLE=${DB_TABLE}
      - NODE_ENV=${NODE_ENV}
